# Site settings
title: OpenTracksApp
description: "OpenTracks is a sport tracking application that completely respects your privacy."
url: "https://www.OpenTracksApp.com"

logo-url: "/static/img/opentracks-logo.svg"

safe: true

permalink: pretty
